### ISSUE TITLE
About TOGL demo

### ISSUE THREAD

**Issue by good-demo** [aidos-lab/pytorch-topological#26] opened 2023-03-07 10:27 UTC
Thansk for your repo in togl
But when I run the demo(graph.py) it will make an error 'Segmentation fault (core dumped)'

**Comment by Pseudomanifold** [comment] 2023-03-07 11:51
More details are required to understand this error. In general, the segmentation fault might indicate an incorrect installation, but without any details, it is hard to diagnose this.

**Comment by good-demo** [comment] 2023-03-07 13:59
Thanks for your reply, when I input  python graphy.py in terminal, it will make an error 'Segmentation fault (core dumped)' without other error

**Comment by good-demo** [comment] 2023-03-07 15:40
Thank you for your suggestion. I will try it next
This program（graph.py） will cause errors on the Linux server
But in Mac OS it works well

**Comment by good-demo** [comment] 2023-03-08 20:09
I have solved this problem by changing the platform, but now there are new problems. Can I run this code on cuda?
When I run graphy.py in cuda it will make an error '''RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)'''

**Comment by Pseudomanifold** [comment] 2023-03-09 08:04
I cannot reproduce this problem and you did not post any specific code. However, I modified the example code to show how to move tensors to the GPU. This is **not** an issue with the TOGL implementation though. Fixed this is in 6bee7e1383fdb93ab154ff3941aef950f807f8d2; please pull the development version to get this to work.

(Closing because issue is fixed; feel free to reopen)

**Closed by Pseudomanifold** 2023-03-09 08:04 UTC
